[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

# Load .env from project root
env_file = "../.env"

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
mantle = "${MANTLE_RPC}"

[etherscan]
mantle = { key = "${MANTLESCAN_API_KEY}", url = "https://api.mantlescan.xyz/api" }
